### ISSUE TITLE
[BUG] Inheritance only works for Aspects, not for Types

### ISSUE THREAD

**Issue by willemi069808** [cap-js/cds-typer#149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

The below code defines an aspect and a type, and subsequently creates two entities that inherit from them. The inheritance from the `type` will throw a typescript error.

### Expected Behavior

To be able to inherit both from aspects as well as types. Types allow for re-using the data structure as an entity property data type so it would be useful to have this.

### Steps To Reproduce

schema.cds file:
```cds
namespace db;

aspect myAspect {
  name : String
｝
type myType {
  name : String
｝

entity E_fromAspect : myAspect {} // works
entity E_fromType : myType {}     // fails
```

service.cds file:
```cds
service MyService {
  entity E_fromAspect as projection on db.E_fromAspect;
  entity E_fromType as projection on db.E_fromType;
}
```

service.ts file:
```ts
import { E_fromAspect, E_fromType } from '#cds-models/MyService'
```

Error from running `tsc`:
```sh
@cds-models/db/index.ts:32:33 - error TS2304: Cannot find name '_myTypeAspect'.
export class E_fromType extends _myTypeAspect(_E_fromTypeAspect(__.Entity)) {}

@cds-models/MyService/index.ts:22:37 - error TS2339: Property '_myTypeAspect' does not exist on type 'typeof import("...")'.
export class E_fromType extends _db._myTypeAspect(_E_fromTypeAspect(__.Entity)) {}

Found 2 errors in 2 files.
Errors Files
@cds-models/db/index.ts: 32
@cds-models/MyService/index.ts: 22
```

### Environment

```markdown
- **OS**: MacOS
- **Node**: 20.11.0
- **npm**: 10.2.4
- **cds-typer**: 0.15.0
- **cds**: 7.5.3
```

**Comment by daogrady** [comment]
Hi Willem,

thanks for reporting this issue! As it turns out, this issue is actually remotely related to [another bug](https://github.com/cap-js/cds-typer/issues/135) which I will address in a [PR](https://github.com/cap-js/cds-typer/pull/150). I checked the sample you provided and found that it fixes the problem. Would you mind checking the PR on your actual model, so we can close this problem en passant if it turns out to fix the issue?

Best,
Daniel
