### ISSUE TITLE
[QUESTION] Usage in conjunction with Feature Toggles

### ISSUE THREAD

**Issue by tsteckenborn** [cap-js/cds-typer#181]
### Question

Currently it seems to me, as if there are no types generated for anything behind a feature flag. Is that intentional?

**Comment by daogrady** [comment]
Hi Tobias,

that is not intentional, no. Could you please give an example where I can observe this? I will then gladly look into it.

Best,
Daniel

**Comment by daogrady** [comment]
Re-tagging as feature request.
Anything hidden behind feature flags has not been generated so far, so we have to take a look at those eventually.

**Comment by tsteckenborn** [comment]
As discussed, this would still be interesting for us, especially if CAP supports trunk based development with Feature Toggles a bit better.

**Comment by daogrady** [comment]
Hi Tobias,

coming back to this, could you please describe your expectations for this feature some more? How would a model with optional feature toggles look like? Would it contain _all_ model parts hidden behind feature toggles, even, if they turn out to be deactivated? 

Best,
Daniel

**Comment by tsteckenborn** [comment]
Hi Daniel,

I assume that here different opinions are necessary (as I also don't know the whole of it's behaviour in CAP). In general afaik on the database the ones behind the feature flag exist. So I'd argue for putting them in as optional parameters.

Or would there be something like different types and importing based on a condition?

**Comment by daogrady** [comment]
Hi Tobias,

as far as I understand feature flags, they can be toggled rather dynamically, while the code generation done by cds-typer is very static. So in order to be "prepared" for a user switching on a certain toggle, the model should probably be available in full? What if the model contains mutually exclusive features, like an entity that has different properties, based on whether it is used in a development environment or prod, each hidden behind a feature toggle, but would collide if included in the model at the same time?

Right now, I'm just trying to understand the expectations behind this requirement. If your requirement is to include a specific feature toggle model, have you tried explicitly passing it to cds-typer?

```sh
cds-typer "*" fts/mytoggle/schema.cds
```
?

Best,
Daniel

**Comment by daogrady** [comment]
Hi @tsteckenborn,

just checking in to see if the above solution already handles your use case? 🙂

Best,
Daniel

**Comment by tsteckenborn** [comment]
Hi Daniel,

Sorry was OOO last week. I'm not sure if that's the best to achieve the desired effect. If I'm not mistaken whether it's the feature flag active variant or not is (or should be) already decided when reaching the ".on" (or similar) handlers. Yet I'd need to check in more detail. In the end it's also about how CAP wants to handle this going forward. More or less right now for me the story around Feature Flags doesn't really work "flawlessly" when trying to have types.

**Comment by daogrady** [comment]
Hi Tobias,

no worries, just wanted to check!

> whether it's the feature flag active variant or not is (or should be) already decided when reaching the ".on" (or similar) handlers. 

"Reaching" as in "running into it at runtime"? Then that is too late for cds-typer to intervene, as it is running purely at design time. The decision whether to generate types for a feature has therefore to be made before the app is even started.

If you already know at design time that you want to enable certain features, then you can pass all relevant model files to cds-typer.

I followed the [tutorial for feature toggles in CAPire](https://cap.cloud.sap/docs/guides/extensibility/feature-toggles#enable-feature-toggles) and by running

```sh
cds-typer "*" fts/isbn/schema.cds --outputDirectory @cds-models
```

I ended up with the entity class containing the desired isbn feature:

```ts
export function _BookAspect<TBase extends new (...args: any[]) => object>(Base: TBase) {
  return class Book extends Base {
    declare ID?: __.Key<number>
    declare title?: string | null
    declare stock?: number | null
    declare isbn?: string | null
    static readonly kind: 'entity' | 'type' | 'aspect' = 'entity';
    declare static readonly keys: __.KeysOf<Book>
    declare static readonly actions: Record<never, never>
  };
}
```

Best,
Daniel

**Comment by daogrady** [comment]
As discussed yesterday, fixing the underlying issue is beyond the scope of cds-typer. Which parts to include in the model is determined by the `@sap/cds`, specifically `cds.load(...)`, which cds-typer just consumes.
Users can specify additional parts of the model by passing the as additional positional arguments to cds-typer, and as of today, this is a decision the users has to make, as model parts could be mutually exclusive and cds-typer has no way to solve this.

If this should change in the future, then it has to happen in `@sap/cds`. A respective internal issue is pending.
