### ISSUE TITLE
[BUG] cds build plugin throws error

### ISSUE THREAD

**Issue by Kyrodan** [cap-js/cds-typer#253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

JavaScript, TypeScript

### Current Behavior

Since v0.21.1 and #248 the plugion is now bundled.
Running `cds build`now throws an exception:
`Error: Illegal priority for  encountered for custom plugin - in this version only priority value '1' is allowed`

### Expected Behavior

Doen't throws exception.

### Steps To Reproduce

run `cds build`

### Environment

```markdown
- **OS**: Windows 10
- **Node**: v20.13.1
- **npm**: 10.8.0
- **cds-typer**: 0.21.1
- **cds**: cds-dk [7.9.2], cds [7.9.2], compiler [4.9.4]
```

### Anything else?

From @sap\cds-dk\lib\build\buildTaskEngine.js:214:19:
![grafik](https://github.com/cap-js/cds-typer/assets/355178/5ed2810c-017d-4c54-beca-90f23c7f863c)

**Comment by daogrady** [comment]
Hi Daniel,

thanks for pointing this out! This happens because I had expected cds8 to be available by now (which is required for this build task to work).
So this is currently a rather unfortunate error message that will automagically fix itself as soon as you are using cds8 (yet to be released!).
Sorry for the inconvenience!

Best,
Daniel

**Comment by daogrady** [comment]
Starting with the upcoming release of cds-typer, the build task will only attempt to run if cds8 is in place to not confront users with this ugly error.
Again, once cds8 is released and in use this problem will go away, but I see how the current output is confusing to users. Thanks again for pointing it out!
