### ISSUE TITLE
[FEATURE] Expose 'keys' & 'gens' as static props per each compiled CDS entity

### ISSUE THREAD

**Issue by siarhei-murkou** [cap-js/cds-typer#294]
### Description

I need to know which CDS property names are marked as CDS keys & which are auto-generated if to not provide them explicitly.

### Suggested Solution

CDS entity with primary key & auto-generated props:

```cds
entity TestObjects: cuid {
  name: String not null;
  description: String;
  type: String not null default 'test';
  updatedAt: Timestamp not null default $now;
}
```

It has to be compiled into:

```TypeScript
class TestObjects {
  ...
  ID: string;
  name: string;
  description: string | null;
  type: string;
  updatedAt: String;
  ...
  /** primary keys of CDS entity */
  static readonly keys: ("ID")[];
  /** auto-generated properties of CDS entity */
  static readonly gens: ("ID" | "type" | "updatedAt")[];
}
```

**Comment by daogrady** [comment]
Hi Siarhei,

I think providing a static `keys` property is perfectly fine, as that is present in CSN during runtime.
![Screenshot 2024-08-13 at 18 50 43](https://github.com/user-attachments/assets/a7feda7d-98bf-4ec0-b2b1-89505524b42e)

One thing that has bitten me in the past for similar scenarios is inheritance. Explicitly listing all keys would probably require `LinkedCSN`, which further cements [the fact that we currently need to carry two flavours of CSN](https://github.com/cap-js/cds-typer/issues/128). I have [played a bit around](https://www.typescriptlang.org/play/?#code/C4TwDgpgBA0hIB4AqA+KBeKSoDIoG8BreALimACcBXCAXwChRJZ4BnAeQDNk1N96oUANowoASwB2UYiAD2nLAF0ySEYqgQAHsAgSAJqxaIqEwhNkB3CWgD8WNVDISIANwgV6DegGMANgENWQwAhfwoCAUEoPQg-MOhJAAt3MR09OBAyDIQJKgBbACN3FE96HwCgqAAxWVkNbV0DKFDw-ijo2ICKBL0ARiz4HPyiihL2mLjuqAl-PIgyVkpJAHNIwQmunoAmAcRFihWxqI34qEX-YDFvaTZdjm4a2RKvR4A6GVZXmbn6N4-XsR9X61d5sAESZIHNIZMr0IA) with deriving a utility type that can automatically include all key elements.
But all in all, I don't see any reason why there shouldn't be a static `keys` property.

The other part of your suggestion I am less sure about. I don't seem to see a static `gen` property in CSN, so that would be something that would purely exist in the world cds-typer is fabricating on type level. I am trying to avoid that as much as possible. Could you maybe point out where you found `gen`, if that can be present in the resulting CSN?

Best,
Daniel

**Comment by daogrady** [comment]
Hi Siarhei,

I have put up a [PR](https://github.com/cap-js/cds-typer/pull/308) that introduces a static `.keys` property that contains all the keys in your entities. Feel free to check if that was what you were looking for.

Best,
Daniel

**Comment by daogrady** [comment]
Note to self: the static `.gen` property OP asked for is a list of properties that have a `default` value and would therefore automatically generate a correponding value on write operations.
As this can not be found in CSN during runtime, this particular part of the request is a _wontfix_ for now. But we could at some point in the future expand the type of each property to contain more information that is actually contained in the CSN:

```ts
class Book {
  createdAt: CDSDate & { default?: string }
}
```
