### ISSUE TITLE
[BUG] cds build fails with cds typer

### ISSUE THREAD

**Issue by qby-ankul** [cap-js/cds-typer#405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

cds build throws an error for the cds typer. Furthermore, the resources are also generated at root level with the current version. Example project is a freshly generated one.

https://github.com/qby-ankul/cds-typer-assoc/blob/main/buildError.txt

### Expected Behavior

No error on build and working association.

### Steps To Reproduce

`cds build` in repo

### Environment

```markdown
BAS

user: typer-test $ cds -v

@cap-js/asyncapi: 1.0.2
@cap-js/cds-typer: 0.29.0
@cap-js/cds-types: 0.7.0
@cap-js/db-service: 1.15.1
@cap-js/openapi: 1.0.7
@cap-js/sqlite: 1.7.7
@sap/cds: 8.4.2
@sap/cds-compiler: 5.4.4
@sap/cds-dk: 8.4.2
@sap/cds-dk (global): 8.4.2
@sap/cds-fiori: 1.2.7
@sap/cds-foss: 5.0.1
@sap/cds-mtxs: 2.3.1
@sap/eslint-plugin-cds: 3.1.2
Node.js: v20.12.0
home: /home/user/projects/typer-test/node_modules/@sap/cds
typer-test: 1.0.0
```

### Repository Containing a Minimal Reproducible Example

https://github.com/qby-ankul/cds-typer-assoc/

**Comment by YoussefBoudiba** [comment]
Having the same issue since v0.29.0

**Comment by stockbal** [comment]
It seams the new option `target_module_type` causes an early initialization of the Configuration module:

https://github.com/cap-js/cds-typer/blob/30e777d2f08af61d87261ed4faf777ee7f3d9a5d/lib/file.js#L149-L151

which in turn makes the following lines have no effect and the `outputDirectory` remains at its default `.` instead of the automatic determined folder `@cds-models`

https://github.com/cap-js/cds-typer/blob/30e777d2f08af61d87261ed4faf777ee7f3d9a5d/cds-plugin.js#L97-L98

You can work around that problem by specifying the output directory in the package.json 

```json
{
  ...
  "cds": {
    "typer": {
      "output_directory": "@cds-models"
    }
  }
  ...
}
```

**Comment by daogrady** [comment]
Hi everyone,

thanks for reporting this issue! I will push out a fix-release asap to address this problem.
Also thanks @stockbal for providing an analysis of the problem.

Best,
Daniel

**Comment by qby-ankul** [comment]
@stockbal thank you very much. The definition fix the problem.

`{
  ...
  "cds": {
    "typer": {
      "output_directory": "@cds-models"
    }
  }
  ...
}`

**Comment by qby-ankul** [comment]
I'll try to create a issue in the next few days
